Added hJoe v2 token
traderjoe-xyz/joe-tokenlists pull request #545
Opened 2022-08-10 08:24 UTC by blenessy

A bit confusing as they have both a hJoe v1 and v2 tokens with the
same symbol. Since v2 deprecated v1, I will not bother adding it.

2022-08-18 04:19 UTC, 0xmurloc requested changes

2022-08-18 04:19 UTC, 0xmurloc commented on joe.tokenlist.json
>    "timestamp": "2021-08-06T00:00:00+00:00"
pls bump the date

2022-08-19 06:50 UTC, blenessy commented on joe.tokenlist.json
>    "timestamp": "2021-08-06T00:00:00+00:00"
sure, np

2022-08-19 06:50 UTC, blenessy commented on joe.tokenlist.json
>    "timestamp": "2021-08-06T00:00:00+00:00"
done

2022-08-22 02:08 UTC, 0xmurloc commented
added separate commit

2022-08-22 02:08 UTC, closed without merging